// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
  "/categories": {
    params: {};
  };
  "/restpreview/:rest_id": {
    params: {
      "rest_id": string;
    };
  };
  "/cart": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/blog/:article_id": {
    params: {
      "article_id": string;
    };
  };
  "/contact": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/signin": {
    params: {};
  };
  "/forgetpassword": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/*" | "/categories" | "/restpreview/:rest_id" | "/cart" | "/pricing" | "/blog" | "/blog/:article_id" | "/contact" | "/signup" | "/signin" | "/forgetpassword";
  };
  "components/pages/catchall.tsx": {
    id: "components/pages/catchall";
    page: "/*";
  };
  "components/pages/main_layout.tsx": {
    id: "components/pages/main_layout";
    page: "/" | "/categories" | "/restpreview/:rest_id" | "/cart" | "/pricing" | "/blog" | "/blog/:article_id" | "/contact";
  };
  "components/pages/home.tsx": {
    id: "components/pages/home";
    page: "/";
  };
  "components/pages/category_filter.tsx": {
    id: "components/pages/category_filter";
    page: "/categories";
  };
  "components/pages/restaruant_preview.tsx": {
    id: "components/pages/restaruant_preview";
    page: "/restpreview/:rest_id";
  };
  "components/pages/cart.tsx": {
    id: "components/pages/cart";
    page: "/cart";
  };
  "components/pages/pricing.tsx": {
    id: "components/pages/pricing";
    page: "/pricing";
  };
  "components/pages/blog.tsx": {
    id: "components/pages/blog";
    page: "/blog";
  };
  "components/pages/article_layout.tsx": {
    id: "components/pages/article_layout";
    page: "/blog/:article_id";
  };
  "components/pages/article0.tsx": {
    id: "components/pages/article0";
    page: "/blog/:article_id";
  };
  "components/pages/customer_support.tsx": {
    id: "components/pages/customer_support";
    page: "/contact";
  };
  "components/pages/auth_layout.tsx": {
    id: "components/pages/auth_layout";
    page: "/signup" | "/signin" | "/forgetpassword";
  };
  "components/pages/sign_up.tsx": {
    id: "components/pages/sign_up";
    page: "/signup";
  };
  "components/pages/sign_in.tsx": {
    id: "components/pages/sign_in";
    page: "/signin";
  };
  "components/pages/forget_password.tsx": {
    id: "components/pages/forget_password";
    page: "/forgetpassword";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "components/pages/catchall": typeof import("./src/components/pages/catchall.tsx");
  "components/pages/main_layout": typeof import("./src/components/pages/main_layout.tsx");
  "components/pages/home": typeof import("./src/components/pages/home.tsx");
  "components/pages/category_filter": typeof import("./src/components/pages/category_filter.tsx");
  "components/pages/restaruant_preview": typeof import("./src/components/pages/restaruant_preview.tsx");
  "components/pages/cart": typeof import("./src/components/pages/cart.tsx");
  "components/pages/pricing": typeof import("./src/components/pages/pricing.tsx");
  "components/pages/blog": typeof import("./src/components/pages/blog.tsx");
  "components/pages/article_layout": typeof import("./src/components/pages/article_layout.tsx");
  "components/pages/article0": typeof import("./src/components/pages/article0.tsx");
  "components/pages/customer_support": typeof import("./src/components/pages/customer_support.tsx");
  "components/pages/auth_layout": typeof import("./src/components/pages/auth_layout.tsx");
  "components/pages/sign_up": typeof import("./src/components/pages/sign_up.tsx");
  "components/pages/sign_in": typeof import("./src/components/pages/sign_in.tsx");
  "components/pages/forget_password": typeof import("./src/components/pages/forget_password.tsx");
};